import { Metadata } from "next";

export const sharedMetadata: Metadata = {
    metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL as string),
    title: "APEX LMS | Empowering organizations and individuals with the tools and knowledge they need to excel in today's competitive landscape.",
    description: "At APEX LMS, we are dedicated to empowering organizations and individuals with the tools and knowledge they need to excel in today's competitive landscape. With a comprehensive suite of services spanning management and leadership consultancy, educational support activities, and specialized office support services, we are your trusted partner in achieving excellence.",
    icons: ['/favicon.ico'],
    openGraph: {
        title: 'APEX LMS ',
        description: ' Empowering organizations and individuals with the tools and knowledge they need to excel in today\'s competitive landscape.',
        siteName: 'APEX LMS',
        images: ['/opengraph-image.png'],
        type: 'website',
        countryName: 'RWANDA',
        url: process.env.NEXT_PUBLIC_SITE_URL as string,
        phoneNumbers: ['+250789553464'],
        emails: ['info@apexlms.rw'],
    },
    keywords: [
        "APEX LMS",
        "leadership consultancy",
        "management consultancy",
        "educational support",
        "office support services",
        "strategic management",
        "curriculum development",
        "professional growth",
        "education consultancy",
        "business excellence",
        "document preparation",
        "photocopying services",
        "printing services",
        "management solutions",
        "leadership development",
        "organizational success",
        "business growth",
        "corporate training",
        "personal development",
        "consultancy services",
        "learning management",
        "professional training",
        "employee development",
        "leadership skills",
        "management training",
        "customized solutions",
        "team performance",
        "executive coaching",
        "skill enhancement",
        "operational efficiency",
        "expert guidance",
        "leadership skills training",
        "performance improvement",
        "organizational excellence",
        "talent development",
        "team building",
        "growth strategy",
        "success coaching",
        "knowledge sharing",
        "industry expertise",
        "education services",
        "workforce development",
        "academic excellence",
        "staff training",
        "office efficiency",
        "learning enhancement",
        "professional consulting",
        "strategic development",
        "leadership coaching",
        "corporate leadership",
        "executive training",
        "management consultancy Rwanda",
        "educational consultancy Rwanda",
        "document services Rwanda",
        "office services Rwanda",
        "leadership consultancy Rwanda",
        "business consulting Rwanda",
        "educational support Rwanda",
        "professional services Rwanda",
        "personal growth Rwanda",
        "office management Rwanda",
        "organizational development",
        "Rwanda business services",
        "Rwanda office support",
        "management consultancy firm",
        "leadership consultancy firm",
        "business strategy",
        "performance management",
        "business efficiency",
        "industry leaders",
        "professional excellence",
        "career advancement",
        "education and training",
        "professional development Rwanda",
        "education consultancy Africa",
        "learning management solutions",
        "corporate solutions",
        "corporate training Rwanda",
        "consultancy experts",
        "tailored business solutions",
        "professional guidance",
        "management"
    ],
};